In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('global_power_plant_database.csv')
df.head()

C:\Users\ronen\AppData\Local\Temp\ipykernel_17864\2844434236.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('global_power_plant_database.csv')

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017,estimated_generation_note_2013,estimated_generation_note_2014,estimated_generation_note_2015,estimated_generation_note_2016,estimated_generation_note_2017
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.0,32.322,65.1190,Hydro,NaN,NaN,...,123.77,162.90,97.39,137.76,119.50,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
1,AFG,Afghanistan,Kandahar DOG,WKS0070144,10.0,31.670,65.7950,Solar,NaN,NaN,...,18.43,17.48,18.25,17.70,18.29,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
2,AFG,Afghanistan,Kandahar JOL,WKS0071196,10.0,31.623,65.7920,Solar,NaN,NaN,...,18.64,17.58,19.10,17.62,18.72,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
3,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.0,34.556,69.4787,Hydro,NaN,NaN,...,225.06,203.55,146.90,230.18,174.91,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
4,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.0,34.641,69.7170,Hydro,NaN,NaN,...,406.16,357.22,270.99,395.38,350.80,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34936 entries, 0 to 34935
Data columns (total 36 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country                         34936 non-null  object
 1   country_long                    34936 non-null  object
 2   name                            34936 non-null  object
 3   gppd_idnr                       34936 non-null  object
 4   capacity_mw                     34936 non-null  float64
 5   latitude                        34936 non-null  float64
 6   longitude                       34936 non-null  float64
 7   primary_fuel                    34936 non-null  object
 8   other_fuel1                     1944 non-null   object
 9   other_fuel2                     276 non-null    object
 10  other_fuel3                     92 non-null     object
 11  commissioning_year              17447 non-null  float64
 12  owner                           20868 non-null  object
 13  source                          34921 non-null  object
 14  url                             34918 non-null  object
 15  geolocation_source              34517 non-null  object
 16  wepp_id                         16234 non-null  object
 17  year_of_capacity_data           14887 non-null  float64
 18  generation_gwh_2013             6417 non-null   float64
 19  generation_gwh_2014             7226 non-null   float64
 20  generation_gwh_2015             8203 non-null   float64
 21  generation_gwh_2016             9144 non-null   float64
 22  generation_gwh_2017             9500 non-null   float64
 23  generation_gwh_2018             9637 non-null   float64
 24  generation_gwh_2019             9659 non-null   float64
 25  generation_data_source          11400 non-null  object
 26  estimated_generation_gwh_2013   16120 non-null  float64
 27  estimated_generation_gwh_2014   16503 non-null  float64
 28  estimated_generation_gwh_2015   17050 non-null  float64
 29  estimated_generation_gwh_2016   17570 non-null  float64
 30  estimated_generation_gwh_2017   33138 non-null  float64
 31  estimated_generation_note_2013  34936 non-null  object
 32  estimated_generation_note_2014  34936 non-null  object
 33  estimated_generation_note_2015  34936 non-null  object
 34  estimated_generation_note_2016  34936 non-null  object
 35  estimated_generation_note_2017  34936 non-null  object
dtypes: float64(17), object(19)
memory usage: 9.6+ MB

In [6]:
df_new = df[['country','country_long','name','capacity_mw','latitude','longitude','primary_fuel']]

In [7]:
df_new

,country,country_long,name,capacity_mw,latitude,longitude,primary_fuel
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,33.0,32.3220,65.1190,Hydro
1,AFG,Afghanistan,Kandahar DOG,10.0,31.6700,65.7950,Solar
2,AFG,Afghanistan,Kandahar JOL,10.0,31.6230,65.7920,Solar
3,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,66.0,34.5560,69.4787,Hydro
4,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,100.0,34.6410,69.7170,Hydro
...,...,...,...,...,...,...,...
34931,ZMB,Zambia,Ndola,50.0,-12.9667,28.6333,Oil
34932,ZMB,Zambia,Nkana,20.0,-12.8167,28.2000,Oil
34933,ZMB,Zambia,Victoria Falls,108.0,-17.9167,25.8500,Hydro
34934,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,920.0,-18.3835,26.4700,Coal
34935,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,750.0,-16.5222,28.7619,Hydro

In [8]:
df_new.to_csv('global_power_plant_modified.csv', index=False)